#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include"DIO_interface.h"
#include "SEVENSEG_config.h"
#include "SEVENSEG_interface.h"
#include "SEVENSEG_private.h"

u8 LastNumber= SEVENSEG_INITIAL_VAL;
u8 SEVENSEG_Enable_Ports[2]={SEVENSEG1_ENABLE_PORT,SEVENSEG2_ENABLE_PORT};
u8 SEVENSEG_Enable_PINS[2]={SEVENSEG1_ENABLE_PIN,SEVENSEG2_ENABLE_PIN};



void SEVENSEG_SetNumber(u8 Number)
{
	u8 SEVENSEG_NUMBERS[10]={0b00111111,0b00000110,0b01011011,0b01001111,0b01100110,0b01101101,0b01111101,0b00000111,0b01111111,0b01101111};

	#if SEVENSEG_MODE == 1
		SetPinValue(SEVENSEG_A_PORT,SEVENSEG_A_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],0));
		SetPinValue(SEVENSEG_B_PORT,SEVENSEG_B_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],1));
		SetPinValue(SEVENSEG_C_PORT,SEVENSEG_C_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],2));
		SetPinValue(SEVENSEG_D_PORT,SEVENSEG_D_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],3));
		SetPinValue(SEVENSEG_E_PORT,SEVENSEG_E_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],4));
		SetPinValue(SEVENSEG_F_PORT,SEVENSEG_F_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],5));
		SetPinValue(SEVENSEG_G_PORT,SEVENSEG_G_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],6));
		SetPinValue(SEVENSEG_H_PORT,SEVENSEG_H_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],7));

	#elif SEVENSEG_MODE == 0
		SetPinValue(SEVENSEG_A_PORT,SEVENSEG_A_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],0)^0x01);
		SetPinValue(SEVENSEG_B_PORT,SEVENSEG_B_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],1)^0x01);
		SetPinValue(SEVENSEG_C_PORT,SEVENSEG_C_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],2)^0x01);
		SetPinValue(SEVENSEG_D_PORT,SEVENSEG_D_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],3)^0x01);
		SetPinValue(SEVENSEG_E_PORT,SEVENSEG_E_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],4)^0x01);
		SetPinValue(SEVENSEG_F_PORT,SEVENSEG_F_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],5)^0x01);
		SetPinValue(SEVENSEG_G_PORT,SEVENSEG_G_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],6)^0x01);
		SetPinValue(SEVENSEG_H_PORT,SEVENSEG_H_PIN,GET_BIT(SEVENSEG_NUMBERS[Number],7)^0x01);
	

	#endif

	LastNumber=Number;
}

void SEVENSEG_Enable(u8 SEVENSEG_NUMBER)
{
	#if SEVENSEG_MODE == 1
    	SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER],SEVENSEG_Enable_PINS[SEVENSEG_NUMBER],0);
  	#elif SEVENSEG_MODE == 0
    	SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER],SEVENSEG_Enable_PINS[SEVENSEG_NUMBER],1);
    #endif

    /* to display last value of SEVENSEG after enabling it */
    SEVENSEG_SetNumber(LastNumber);

	//SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER] ,SEVENSEG_Enable_PINS[SEVENSEG_NUMBER], SEVENSEG_MODE^0X01);
	//SEVENSEG_SetNumber(LastNumber);
}

void SEVENSEG_Disable(u8 SEVENSEG_NUMBER)
{

	#if SEVENSEG_MODE == 1
	   SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER],SEVENSEG_Enable_PINS[SEVENSEG_NUMBER],1);
	#elif SEVENSEG_MODE == 0
	   SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER],SEVENSEG_Enable_PINS[SEVENSEG_NUMBER],0);
	#endif


	//SetPinValue(SEVENSEG_Enable_Ports[SEVENSEG_NUMBER] ,SEVENSEG_Enable_PINS[SEVENSEG_NUMBER] , SEVENSEG_MODE);
    
    
}
